apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Create the istio-system namespace after the operator CRD is created
spec:
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: istio-system
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}