apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    namespace: sock-shop
    server: {{ .Values.spec.default.destination.server }}
  project: default
  source:
    path: sock-shop
    repoURL: {{ .Values.spec.sockShop.source.repoURL }}
    targetRevision: {{ .Values.spec.sockShop.source.targetRevision }}